// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMCommanLayer.Models;

namespace QuantityMesurement_API.Migrations
{
    [DbContext(typeof(QuantityMesurementContext))]
    [Migration("20200707113124_QMCommanLayer.Models.QuantityMesurementContext")]
    partial class QMCommanLayerModelsQuantityMesurementContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QMCommanLayer.QuantityMesurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConversionType")
                        .IsRequired();

                    b.Property<DateTime>("DateOFCreation");

                    b.Property<double>("Result");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("QuantityMesurementTable");
                });
#pragma warning restore 612, 618
        }
    }
}
